#!/bin/bash

# Use podman if available; otherwise fallback to docker
PODMAN=$(which podman > /dev/null 2>&1)
IMG_TAG="bike-finder:latest"

if [ $? -eq 0 ]; then
    CBUILDER=podman

elif [ $? -eq 1 ]; then
    CBUILDER=docker
fi

${CBUILDER} build --quiet --tag ${IMG_TAG} --file containerfile
${CBUILDER} run ${IMG_TAG}