#!/bin/bash

# Use podman if available; otherwise fallback to docker
PODMAN=$(which podman > /dev/null 2>&1)
IMG_TAG="bike-finder:latest"

if [ $? -eq 0 ]; then
    podman build --tag ${IMG_TAG} --file containerfile
    podman run ${IMG_TAG}
elif [ $? -eq 1 ]; then
    docker build --tag ${IMG_TAG} --file containerfile
    docker run ${IMG_TAG}
fi
